# Generated by Django 4.0.4 on 2022-05-18 11:47

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.nameFile),
        ),
    ]
