# Generated by Django 4.0.4 on 2022-05-19 10:45

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.nameFile),
        ),
    ]
